export const DECK_CHANNELS = {
  GET_BY_AVG_MASTERY: 'GET_BY_AVG_MASTERY',
  GET: 'GET_DECKS',
  CREATE: 'CREATE_DECK',
  DELETE: 'DELETE_DECK',
  UPDATE: 'UPDATE_DECK',
  GET_BY_ID: 'GET_DECK_BY_ID',
};
export const APP_CONFIG_CHANNELS = {
  GET_CONFIG: 'get-app-config',
  SET_CONFIG: 'set-app-config',
};

export const FLASHCARD_CHANNELS = {
  GET_BY_DECK_ID: 'GET_FLASHCARDS_BY_DECK_ID',
  CREATE: 'CREATE_FLASHCARD',
  DELETE: 'DELETE_FLASHCARD',
  UPDATE: 'UPDATE_FLASHCARD',
  GET_RANDOM: 'GET_RANDOM_FLASHCARDS',
};
